### ISSUE TITLE
Missing Discoverability Features

### ISSUE THREAD

**Issue by SirLich** [redjaguar-sapiens/foodies#1]
You can set the 'sapiens-mode' tag on the repo, to help people find it. For example: https://github.com/topics/sapiens-mod. You can set the description of the repo as well!

If you want, you could also put an invite link to the Sapiens Modding Discord: https://discord.gg/WnN8hj2Fyg

You can mention you offer support there, and that helps grow the community.

**Comment by redjaguar-sapiens** [comment]
Fixed!
